### ISSUE TITLE
Feature: User Can Edit Workouts on Workout Page (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit workout information to change either the workout date or description.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the small edit icon attached to any workout card pulls up an "Edit Workout" `modal` that is prefilled with the clicked workout's date and description. Changes within this modal are saved and change the workout.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![All Workouts (4)](https://user-images.githubusercontent.com/105157437/200694791-deb0a98b-f43f-4d37-9f02-a2f1e126d3fd.png)
![All Workouts (5)](https://user-images.githubusercontent.com/105157437/200694796-bc407c21-328f-46c3-8ccd-4fbd0d09a749.png)

![Desktop_ My Runs_ Workouts 2 (2)](https://user-images.githubusercontent.com/105157437/200695808-6b941eb0-fff2-4451-9097-5d9205c857a0.png)
![Desktop_ My Runs_ Details 4 (1)](https://user-images.githubusercontent.com/105157437/200695814-6be6709e-4cc4-4828-9b21-69c9f1821f5c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a `PUT` route to `/api/workouts` for editing data. The route should take an entryId as a parameter.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add an edit button to the top left of all workout cards matching the wireframe.
- [x] `onClick` of the edit button, pass the information of that workout to the workout form to prefill it. 
- [x] Ensure that hash routing works properly with the edited data --> entering an id into the `URL` should pull up that workout in edit mode if it exists, or give the user an appropriate error message if it does not.
- [x] `onSubmit` of the workout-form when in edit mode, send a `fetch` request to the backend route coded above.
- [x] Ensure that a `loadingSpinner` appears while data is moving, and that `networkError` is also caught.
- [x] After a successful submit, navigate the user back to the `myWorkouts` page where they can view their edited workout.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
