### ISSUE TITLE
Feature: User Can Delete Workouts on Workout Page (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete their custom workouts.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After clicking on the edit button to the right of the workout text and opening the "Edit Workout" `modal`, users can click `delete` to delete their workouts. Users must confirm the delete through a snackbar before the delete goes through.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![All Workouts (9)](https://user-images.githubusercontent.com/105157437/200702044-25a0461c-5b7a-4e2d-8d23-6a7ad99fb8e2.png)
![My Page -- Confirm Delete (2)](https://user-images.githubusercontent.com/105157437/200702157-98424e03-5f3e-460b-a353-fb2e7711dab6.png)
![All Workouts (7)](https://user-images.githubusercontent.com/105157437/200701627-d6c45f8d-5ada-4bc6-a64a-e76ab79d82da.png)

![Desktop_ My Runs_ Workouts 2 (3)](https://user-images.githubusercontent.com/105157437/200701864-4425d6ed-3be2-479e-951c-b9af8df07dee.png)
![Desktop_ My Runs_ Workouts 4](https://user-images.githubusercontent.com/105157437/200701868-281217ec-d3df-48ac-94ee-1ec966ca6f06.png)
![Desktop_ My Runs_ Workouts 5](https://user-images.githubusercontent.com/105157437/200701874-bc8809c2-7186-4923-bb53-d605cc1b3052.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a `DELETE` route to `index.js` that takes a workoutId as a parameter and removes that workout from the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client.

### ⚡ Client Tasks

- [x] Add `fetch` request to the `deleteWorkout` method in `MyWorkouts` component to delete a workout using the delete route coded above.
- [x] Debug the `DeleteSnackbar` placement for the `MyWorkouts` component on delete confirm.
- [x] Ensure that the `DeleteSnackbar` does not create a horizontal scroll bar when pulled up on both the `MyWorkouts` component AND the `Runs` component
- [x] Ensure that while a workout is being deleted, the `LoadingSpinner` component is shown.
- [x] Ensure that if a network error occurs, the `NetworkError` component is shown.
- [x] Ensure that the workout is removed from both the database AND the `MyWorkouts` screen after delete.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
