### ISSUE TITLE
Feature: User Can Search Their Previous Runs

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter their previous runs via a searchbar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By typing either a month, date, or run name into the search bar, users can filter their runs by the entered criteria.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Page -- Activities (2)](https://user-images.githubusercontent.com/105157437/200704390-306de0e7-a221-4e84-9ead-7716ef44a903.png)
![My Page -- Search](https://user-images.githubusercontent.com/105157437/200704393-c5c65ce0-7139-430d-b3a0-fca16c646503.png)

![Desktop_ Activites 2 (1)](https://user-images.githubusercontent.com/105157437/200704503-9049adef-9a5d-4ca8-992e-6a1e66adb26b.png)
![Desktop_ Activities Search](https://user-images.githubusercontent.com/105157437/200704505-0aa370fa-1cb8-41f2-b14e-7dfef17b06a1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Refactor activities component --> Add `FilteredRuns` component and move all `RunMiniCard` code (including map) into that component for easy data movement after searchbar filter.
- [x] Change `searchbar input` to a controlled input --> state should update with content in searchbar.
  - [x] Look out for escape characters, thoroughly test searchbar content via React dev tools.
- [x] Each time searchbar is updated in state, render will be called. Add a method to `activities` that will filter the runs and store the filtered runs in state.
- [ ] Ensure that when the searchbar is empty, all runs are returned if there are runs present. If there are no runs present, the default no runs message should still render.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
