### ISSUE TITLE
Feature: User Can Search Their Previous Workouts

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter their previous workouts via a searchbar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By typing either a month, date, or description into the search bar, users can filter their runs by the entered criteria.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![All Workouts (10)](https://user-images.githubusercontent.com/105157437/200704772-d9b25371-90a3-484e-94d7-5d41ed628002.png)
![All Workouts -- Search](https://user-images.githubusercontent.com/105157437/200704788-b6a78e69-3a24-4fff-9080-ab2003c5d2a5.png)

![Desktop_ My Runs_ Workouts 2 (4)](https://user-images.githubusercontent.com/105157437/200704990-157fe1d1-7c9f-4eff-afda-bc6e73ed6e4e.png)
![Desktop_ My Runs_ Workouts Search](https://user-images.githubusercontent.com/105157437/200705046-d7c2169b-4dc4-4a98-afac-1ca4d4687de4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component, `FilteredWorkouts` to render the filtered workouts. Move relevant code to this component.
- [x] Create a function, `filterWorkouts` to filter workouts using the text the user inputs into the search field. Check to see if `filterRuns` can be reused.
- [x] Ensure that `filterWorkouts` correctly outputs the correct workouts for various inputs with special characters, spaces, etc.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
