### ISSUE TITLE
Feature: User Can Add Rest Days to their Progress Squares

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add rest days into their progress squares either one at a time or on a weekly interval.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking the bed icon in the progress square card, a `modal` will open allowing the user to select a weekly rest day and input individual dates to use as rest days. These days will render blue initially on the progress square chart.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Page -- Progress (5)](https://user-images.githubusercontent.com/105157437/200706470-a6f22929-1f99-48cc-aafc-6f5db6fb379d.png)
![My Page -- Rest Days](https://user-images.githubusercontent.com/105157437/200706474-4c0f23fd-2a1c-4090-98a2-537957c07d40.png)

![Desktop_ My Runs_ Progress Sq 2 (4)](https://user-images.githubusercontent.com/105157437/200706412-bdfdc67c-1e3e-48fb-a23e-3e01359ac8e3.png)
![Desktop_ My Runs_ Progress Sq 4](https://user-images.githubusercontent.com/105157437/200706417-81b1e376-cdaa-467e-92c0-43811b5e957e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include a `restDays` table with the columns `userId`, `date`, and `restId`.
- [x] Add some sample rest days to `data.sql`.
- [ ] Add the `weeklyRestDay` property to the profile table and set its default value to `None` when new users create a profile.

### ☁️ Server Tasks

- [x] Update the `/api/progress` route to also grab the `restData` for future use.
- [x] Add a route for POSTing rest data to the `restDays` table.
- [x] Add a route for PUTting weekly rest day data to the `profile` table.
- [x] Test with HTTPie.
- [x] Respond to the client appropriately.

### ⚡ Client Tasks

- [x] Add a new component `rest-day-modal`.
- [x] Matching the wireframe, code up a modal that pops up `onClick` of the bed icon.
- [x] After adding a rest day, the run should appear in the modal but NOT store in the database.
  - [x] Store new rest days separately and only update the database if new rest days are entered.
- [x] After adding a weeklyRestDay, state should update to store that rest day.
- [x] `onSubmit` of the form, call the two previous routes and update the database with the new data.
- [x] Use the calender picker already installed via npm for grabbing the rest day dates.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
