### ISSUE TITLE
Feature: User Can Add GPS Data (.gpx) to Runs

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#22]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add GPS data from a GPS watch to runs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Within the "Add Run" view, the user can click the `Upload here` button to upload .gpx data. This data pulls up the google map for their run in addition to prefilling the other fields for pace, distance, etc.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add A Run 2 (1)](https://user-images.githubusercontent.com/105157437/200706907-51f288e7-4753-4cd1-8f54-d1c8f20a9ccb.png)
![Desktop_ Add Run 2 (1)](https://user-images.githubusercontent.com/105157437/200706918-006d5688-7dc5-427d-a44c-233883583503.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a `POST` route for posting .gpx data to the database. 
- [x] Test with HTTPie and some sample data.
- [x] Find and install an XML parser from `npm` compatible with project.
- [x] Upload sample `.xml` data to the public folder for test-use.
- [x] Parse `.xml` file into an object. Grab `latitude`, `longitude`, `elevation`, and `speed` from each data point.
- [x] Ensure all data is properly uploaded into the database.

### ⚡ Client Tasks

- [x] Within the `run-form`, add a section for uploading `gpx` data.
- [x] `onClick` of the button, prompt the user to upload their .gpx data and validate it as valid `.xml`.
- [x] Add a `fetch` request to `run-form` that uses `formData` and `.append` to append the file to the request.
- [x] Put `formData` on the request body and send it to the backend for parsing.
- [x] Ensure `formData` and `hasGpx` are cleared in state after.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
