### ISSUE TITLE
Bug: Parameter errors on server-side are not handled properly

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#61]
#### Desired Behavior

> ##### The app should ...

When an invalid parameter is send to the server, the server should respond with an appropriate error message.

#### Actual Behavior

> ##### The app does this instead ...

The server responds with an empty 200 (OK) request.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Using HTTPie, send the server a `PUT` or `DELETE` request for a `runId` or `workoutId` that does not exist.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Add a helper function `handleParameterErrors` to server folder that takes `req` and `res` as arguments.
- [x] Within all code blocks on server-side that use parameters, add a check to ensure the database contains that data before sending a response.
  - [x] If the data does not exist, send a `404` error if the parameterId does not exist.
  - [x] If the data does exist, move the previous code inside of the `if` block to ensure it only runs when the parameter is found in advance.
- [x] Triple-check on the client-side that none of the edit / delete `fetch` requests are broken due to this change.
 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
