### ISSUE TITLE
Feature: User can View GPS Data on Runs Page

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#66]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their `.GPX` data in `MainRunCard`.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on a run on the runs page, if they have `.gpx` data uploaded, their route will show in `MainRunCard.`

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a route for grabbing `GPX` data for all entries. Ensure data is formatted so that all entries are combined into one object with `entryId` as the key and an array of all the `lat/lon` data as a value.
- [x] Thoroughly test the route with HTTPie.
- [x] Respond to the client.

### ⚡ Client Tasks

- [x] Send a `fetch request to the route above after the `fetch` request for regular runData is returned.
- [x] Ensure that the data loads correctly and store it in state as `gpxData`.
- [x] When rendering a `RunMainCard` component, check if `gpxData` has a key for the `entryId` being rendered. If it does, pull the GPS data and use it to render a `Map`.
- [x] If there is no key, render the `NoGpxData` component instead. Style it.
- [x] Ensure that on screens with heights less than 700px there is no overflow off the top of the screen.
- [x] On `RunMiniCard`, check for `gpxData` at the current `entryId` just like with `runMainCard`.
- [x] If the key is found, render an `embedGoogleMap` for that data using an `iframe`.
- [x] If no key is found, render the `NoGpxData` component instead. Style it.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
