### ISSUE TITLE
Feature: User can Edit GPS Data

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#69]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their GPS data when they choose to edit a run.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the edit button on the main run card, if they have GPS data uploaded for that run it will also prefill into the run form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
...

### ☁️ Server Tasks

- [x] Update `server/index.js` `GET` route for runs with an `entryId` as a parameter.
- [x] Check if the run has GPS data --> if it does, pull the data and include the array of lat / lng data in the response.
- [x] Test with HTTPie
- [x] Update `server/index.js` `PUT` route for runs with `entryId` as a parameter.
- [x] Ensure that if a run did not have GPS data, the `hasGpx` flag is changed and the GPS data is uploaded.
- [x] Ensure that if a run did have GPS data, the new data is uploaded correctly to the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In the `RunForm` component, ensure that the response arrives correctly from the server.
- [x] Check for the `hasGps` flag in the response. If `true`, set the GPS data into state.
- [x] Ensure that the `Maps` component renders the GPS data appropriately, and that changing the GPS data uploads the new data to the database and is reflected on the `Activities` page.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
