### ISSUE TITLE
Feature: User Can Add Custom Workout (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a workout date and description for that workout.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the `My Workouts` page, users can click the `plus FAB` to open a modal for adding a workout. This modal has inputs for date and workout description.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Page -- Add Workout](https://user-images.githubusercontent.com/105157437/207945407-6c37682b-3706-4f0a-9d7d-6936395fa553.png)

![Desktop_ Add Run 4](https://user-images.githubusercontent.com/105157437/207946371-9cfad283-a357-4e40-81c4-c836aed3248d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a section to `index.js` for workout routes.
- [x] Code up a POST route to add a workout for a specific user. Route goes after authorization middleware.
- [x] Test the route with HTTP pie to ensure that it works.

### ⚡ Client Tasks

- [x] Create a page `workouts` that will handle routing for workout related components.
- [x] If a user isn't signed in, redirect them back to `sign-in` auth component.
- [x] Otherwise, return a `div` holding the `workoutForm` component.
- [x] Create the `workoutForm component and import it into the `workout` page.
- [x] Initialize state for `workoutForm` component with date, description, fetchingData, and networkError.
- [x] Code up the `workoutForm` component return jsx code, matching the wireframes provided.
- [x] Add a `handleChange` method to handle changes on the inputs --> ensure when the inputs are changed the new value is stored in state dynamically.
- [x] `onSubmit` of the form, toggle fetchingData to true in state and return the `loadingSpinner` component while the data is coming / going to the server.
- [x] Add a `fetch` route for `POST`ing data to the database. Test the route thoroughly.
- [x] Ensure that on network error, the `networkError` component is returned.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
