### ISSUE TITLE
Feature: User Can Delete Their Custom Rest Data

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#80]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` with a `DELETE` route for restdata.
- [x] Update `server/index.js` `GET` route for restData to also grab restId.
- [x] Delete the restDay with the id from `req.body`.
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add `restId` property from `restDay` route as the key for each `restDay` when mapped over in `CustomRestDays`.
- [x] Add `tempDeletedDays` into state for the `restDayForm`. 
- [x] `onClick` of the delete button for a rest date, remove that rest object from tempRestData. Add that rest object to `tempDeletedDays`.
- [x] `onSubmit` of the form, if there are any days in `tempDeletedDays`, call the `DELETE` route from above and remove the days from the database. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
