### ISSUE TITLE
Feature: User Can View their Rest Days on the Progress Squares Chart

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#81]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add SQL to `progress` route to get the `weeklyRestDay` (if it exists) and all of the custom rest days.
- [x] Store these in the top level progress component **instead** of in `restDayModal`. 
- [x] Ensure restDayModal looks to the top level progress component for its data.
- [x] Remove the unneeded `GET` code in `restDayModal` (it should have been moved to `weeklyRestDay`.

### ⚡ Client Tasks

- [x] In the `filterProgressSquares` component, add an `if` condition to check for custom restDays.
- [x] Add an additional `if` statement to check if the day is a `weeklyRestDay`.
- [x] If a day is a custom restDay or weeklyRestDay, set the `runStatus` to `rest`.
- [x] In the component that renders the progressSquares, check for `runStatus: rest`. Render the square blue for rest days.
- [x] Ensure that when rest days are changed, the page updates on modal close.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
