### ISSUE TITLE
Bug: Nav menus do not close on click outside of the menu.

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/runningfuze#97]
#### Desired Behavior

> ##### The app should ...

The menus should close when anywhere on the screen is clicked outside of the menu.

#### Actual Behavior

> ##### The app does this instead ...

Menus persist.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Click any of the three nav menus. 

1. My Runs Nav menu in navbar.
2. Edit / Delete Menu in Runs.
3. Edit / Delete Menu in Workouts.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Fix My Runs Nav Menu.
- [x] Fix Edit / Delete Menu in runs
- [x] Fix Edit / Delete Menu in workouts
